server:
  port: 8080
  servlet:
    context-path: /project
# 数据源配置
spring:
  datasource:
    jdbcUrl: jdbc:oracle:thin:@192.168.239.128:1521:hghis
    username: wsbauser
    password: wsbauser
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: TestHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR